### ISSUE TITLE
hi / brain dump / general probably obvious thoughts & resources

### ISSUE THREAD

**Issue by matthewmueller** [makojs/core#1]
glad to see you're working on this. I've been wanting something that is a little more web-focused than make, but takes it's good parts (incremental builds, topological dependency sorting, etc.)

i've been experimenting with webpack lately and honestly it's a smorgasbord of features, but they definitely got the plugin system right. even though the plugin logic itself is a mess, it works and it's powerful. it looks like you're making hooks based on some of their hooks, but i'd try and figure out what it's doing right.

also, i thought this build system was kind of cool and make-like, https://github.com/bud/bud not sure if you've seen it, but it's worth taking a look.

one thing i've also been thinking about is that operating directly on the graph is extremely powerful. we should be able to build tools like make, webpack, etc. just by hooking into the dependency graph. every tool right now internally manages it's own dependency graph, but i think this should be flipped – tools use one really solid dependency graph library and build tools on top of it.

**Comment by dominicbarnes** [comment]
Good to hear from you @matthewmueller!

I didn't actually get to playing with Webpack too much, it was too steep of a learning curve for me, so the similarities were unintentional. After all of my work on Component and Duo, I had really solidified my own idea for how I wanted to approach solving the problems they aimed to solve.

This has been evolving over the last few weeks in particular, and I'm actually getting pretty close to using it on more of my own projects. As such, these README's are terrible at explaning things, mostly because stuff was still in flux as I was forming the repos. Now that I've settled on this system, I'll be cleaning up all that documentation so some community can begin to form.

In particular, plugins have the dependency tree/graph at their core, which has made the internals here _very_ concise compared to what I was originally expecting. I'd be happy to run through more internals with you if you're in the area. :)

**Comment by matthewmueller** [comment]
hey man sorry for the the super late response. just had a chance to play with the library and i'm really impressed by how simple everything is when you have access to the tree and also how straightforward the wiki is laid out. nice job!

won't be in SF for the next few months, but i'd definitely be down to do a hangout sometime. in the meantime, i hope to start contributing soon :-)
