### ISSUE TITLE
drop the plugin extensions check? or support extension-less plugins

### ISSUE THREAD

**Issue by matthewmueller** [makojs/core#18]
This is a bit controversial, but i'm finding that knowing all extensions up front before adding plugins can be quite tricky.

Here's an example: https://github.com/matthewmueller/scooby/blob/7b3079f5e729a6021002c209374e33cbe756ec3a/lib/plugins/write/index.js#L36-L60

The goal of this code is to basically write out the remaining files in the dependency tree. Instead of just running this plugin on all the remaining files, I need to dynamically lookup the files in the graph, pull their dependencies and add plugins according to their extensions. This causes ordering problems and makes how I iterate over the dependency graph matter. (ex. `index.css` **prewrite stage** needs to happen before it's dependency's `image.png` **prewrite stage** happens, otherwise additional plugins for `png` won't get run).

I'd like to be able to do this:

```js
mako.prewrite(function (file) {
  // if i don't need to operate on the file
  if (file.type === 'js') return
  
  // operate on the file, add this extension to remaining plugins
  // or just run these plugins for this file inside this plugin.
  mako.use(output(file.type, options))
  mako.use(copy_assets ? copy(file.type) : symlink(file.type))
})
```

An easy way to solve this would be to just adding support for plugins that will always run if there's no specified extension. I think this is safe to do because then the developer's plugin can decide if they want to run their code. I'd almost prefer this in general, that's why I'm wondering if it just makes sense to remove the extension check altogether.

**Comment by dominicbarnes** [comment]
Fetching the list of extensions dynamically is not how I would approach this at all, you're fighting against mako doing this approach. (as you've discovered)

I really don't want to add wildcards, as I'm very certain it will cause cross-pollination between plugins that people inevitably wouldn't want. The purpose of specifying extensions is less about technical capability and more about making builds intentional and deterministic.

What I would recommend instead is to take the approach that [mako-browser](https://github.com/makojs/browser) uses. It basically does all the composition and organizes things by the entry type and adds the plugins for each set of build strategies. There's no reason the build should change dynamically like this, as all the plugins should be defined during that initial configuration step.

**Comment by dominicbarnes** [comment]
From your example, I'm not convinced that mako has to change in this regard. However, I will remain open-minded, as I have considered adding a special-case for `*` to match all files. (but like I said, I'm really worried about plugins clobbering into one another)

**Comment by dominicbarnes** [comment]
I'll add `*` as a special-case for now, I'm still worried about it, but we should wait and see if my concerns are well-founded.

**Comment by matthewmueller** [comment]
Cool, I'd basically like this for 3 plugins: `read`, `stat`, and `output`. So maybe this could be dropped if there was a more standard way of handling these (imo) core plugins.

**Comment by matthewmueller** [comment]
nevermind, i realized this was a bad idea :-D

you're never going to want to read in all the files (ex. images you just want to symlink), and you're also never going to want to write all the files (ex. images again). so having anything universal will probably cause problems. 

good call!
