### ISSUE TITLE
parallelize analyze work across cores

### ISSUE THREAD

**Issue by matthewmueller** [makojs/core#25]
AFAIK the analyze phase of every file is completely independent. we could pretty easily use cluster to spread the work across cores.

It also has the added benefit of not slowing down the CLI UI for large synchronous parsers like (babel)

**Comment by dominicbarnes** [comment]
This would be really cool, I'm not sure what the implications are since cluster uses separate processes though. It is definitely something I'll look into!

**Comment by dominicbarnes** [comment]
Just looking around at the docs for cluster and IPC, I don't think this complexity is something I want to introduce to mako core. Most of the work that mako is orchestrating is async in nature, so I don't expect that to be a bottleneck.

However, I _do_ think there is a lot of value in pushing CPU-intensive tasks into separate worker threads. I think mako-babel, for example, could spin up it's own worker thread/pool for doing this if it turns out to be a bottleneck.

Besides, it will be a lot easier to create a worker process that just accepts and returns strings. You can't really share complex objects, like the mako runner/plugins/config/etc really easily.

**Comment by matthewmueller** [comment]
yah that makes sense. the main issue i was running into was a freezing CLI (for interactive stuff like a spinner), but that can be separated from the builder and perhaps the build itself can be in a separate thread.

**Comment by dominicbarnes** [comment]
If a few plugins re-invent that same wheel, I could forsee exposing something from core. (but probably mostly to reduce boilerplate)
